# Generated by Django 3.2.15 on 2022-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220916_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('content', models.TextField()),
                ('img_field', models.ImageField(
                    upload_to='cloudinary://493494235994288:zTTpGxQKi__Q5xN5tStvSY1DDRA@df4j1glpo')),
            ],
        ),
    ]
