# Generated by Django 3.2.15 on 2022-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_createpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_field',
            field=models.ImageField(default='img_field', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createpost',
            name='img_field',
            field=models.ImageField(upload_to=''),
        ),
    ]
