# Generated by Django 3.2.15 on 2022-09-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220923_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
