# Generated by Django 3.2.15 on 2022-10-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slug',
            field=models.SlugField(default='max_length=150, unique=True', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
