# Generated by Django 3.2.15 on 2022-10-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_reservation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='slug',
        ),
    ]
