# Generated by Django 3.2.15 on 2022-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20221002_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_field', models.DateTimeField()),
                ('phone', models.IntegerField(null=True)),
                ('event', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SendReservation',
        ),
    ]
