# Generated by Django 3.2.15 on 2022-10-04 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0029_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='client_reservation', to='auth.user'),
            preserve_default=False,
        ),
    ]
