# Generated by Django 3.2.15 on 2022-10-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_reservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
    ]
