# Generated by Django 3.2.15 on 2022-10-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_reservation_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='second-scoop/'),
        ),
    ]
