# Generated by Django 3.2.15 on 2022-10-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_contact_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='approved',
        ),
    ]
