# Generated by Django 3.2.15 on 2022-10-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_remove_contact_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
